### ISSUE TITLE
Request: Expand documentation on focus and navigation

### ISSUE THREAD

**Issue by dmitriid** [lightning-tv/solid#10]
I have a very simple grid implementation: https://github.com/dmitriid/lightningjs-repro/blob/master/src/components/Grid.tsx (note, the repo itself is for a separate issue filed against `solid-ui`)

It just dumps [0...n] elements on a grid like

```
   0 .... max elements fitting in a row
   max ... max elements fitting in a row
   ...
```

Once focused... It retains focus on the first element regardless of any keyboard or mouse navigation. In my mental model navigating right would cause `selected`/`activeElement` to switch to next element on the right, but that never happens.

**Comment by chiefcll** [comment]
👋 - I'll work on adding some more documentation around this topic. 

If you look at https://github.com/rdkcentral/solid-ui/blob/main/packages/solid/components/Row/Row.tsx - Row adds a onLeft & onRight keyhandler which is doing the work to update selected and setFocus() on the next element. You'd need to do something similar with your Grid component. Add keyhandlers for each direction and handle setFocus() on each of the elements as the user presses keys. Again you can see how Row does it: https://github.com/rdkcentral/solid-ui/blob/main/packages/solid/utils/handleNavigation.ts#L35

Further, you probably don't need a Grid component. You can easily nest Column, Rows to provide Grid like functionality.

**Comment by dmitriid** [comment]
Thanks! I thought it worked "magically" like [BBC's LRUD](https://github.com/bbc/lrud-spatial), that's why I couldn't wrap my head around it :)

**Comment by chiefcll** [comment]
Added a bit more docs. Closing out

**Comment by dmitriid** [comment]
Thank you!
