### ISSUE TITLE
Images with resizeMode "cover" loses its borderRadius

### ISSUE THREAD

**Issue by t1mp4** [lightning-tv/solid#9]
(Not sure if "issue" or "question")

Images with resizeMode "cover" loses its borderRadius.

This is expected because it clips the element, however, it would be nice if it would keep the borderRadius.

```js
<View style={{ width: 300, height: 300, borderRadius: 12 }}>
    <View
        src="http://some-external-site.com/image.png"
        textureOptions={{
            resizeMode: {
                type: "cover"
            }
        }}
        borderRadius={12}
    />
</View>
```

My workaround right now is to add a transparent overlay with a border and border radius, but it's wonky.

Is there a better method?

**Comment by chiefcll** [comment]
Reposted to Lightning Renderer: https://github.com/lightning-js/renderer/issues/357
